launchpad snapcraft build attempt 06
dvswitch -p 1234 -h 127.0.0.1

(process:31968): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
ERROR: Failed to open file '/usr/local/share/dvswitch/pri-video-source.png': No such file or directory

Adding a apps:&command: section to the snap yaml makes dvswitch/dvgrab/dvsource-files/dvsink-files/dvsource-firewire/dvsource-dvgrab run directly when called from terminal (when using dvswitch.dvgrab dvswitch.dvsource-files/etc). 

For dvswitch it stops complaining about libboost.../libpng... missing, but will (still) refuse to find the DSHAREDIR /usr/local/share/dvswitch *.png and refuse to start even when those files are copied to the native host (which works if the dvswitch binary from the snap is run directly in shell with manually prelinking libraries, ugly but it works).  Also manpages/docs are not linked but not necessary.

Good thing dvgrab within the dvswitch snap works and captures DV via firewire without any special privilege requirements directly to the host user/desktop folder.

The stage/prime folder and final snap of dvswitch does contain usr/local/share/dvswitch/*.png