launchpad snapcraft build attempt 07
The following suggested yaml changes from daniel @ forum.snapcraft.io makes dvswitch gui app launch from snap on ubuntu 17.10 amd64 ( if png paths in "src/dv_selector_widget.cpp" are hardcoded).

Howver the app does crash as soon as you start to feed dv video from file or firewire, probably because at that moment it will draw the png's for the first time on the screen).

dvswitch -p 1234 -h 127.0.0.1

(process:2295): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"

(dvswitch:2295): GdkPixbuf-WARNING **: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
ERROR: Couldn't recognize the image file format for file '/snap/dvswitch/current/usr/local/share/dvswitch/pri-video-source.png'

dvswitch -p 1234 -h 127.0.0.1
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
terminate called after throwing an instance of 'Gtk::IconThemeError'
Aborted (core dumped)